/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Controlador.UsuarioDao;
import Controlador.UsuarioDaoImpl;
import Modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author cristian
 */
public class MantenedorAministrarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form mantenedorAministrarUsuarios
     */
    public MantenedorAministrarUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void limpiar() {
        txtBuscarUsuario.setText("");
        txtClave.setText("");
        txtConfirmarClave.setText("");
        txtNombreUsuario.setText("");
        cbCargo.setSelectedIndex(0);
        cbxNombre.setSelected(false);
        cbxClave.setSelected(false);
        cbxCargo.setSelected(false);
        btnIngresar.setEnabled(true);
        btnActivar.setEnabled(false);
        btnDesactivar.setEnabled(false);
        btnActualizar.setEnabled(false);
        lblEstado.setText("");
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        txtConfirmarClave = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        cbCargo = new javax.swing.JComboBox();
        cbxNombre = new javax.swing.JCheckBox();
        cbxClave = new javax.swing.JCheckBox();
        cbxCargo = new javax.swing.JCheckBox();
        btnBuscarUsuario = new javax.swing.JButton();
        txtBuscarUsuario = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        btnDesactivar = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Administrar los Usuarios");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Nombre usuario:");

        jLabel2.setText("Clave:");

        jLabel3.setText("Confirme clave:");

        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        txtNombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreUsuarioKeyTyped(evt);
            }
        });

        txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveKeyTyped(evt);
            }
        });

        txtConfirmarClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConfirmarClaveKeyTyped(evt);
            }
        });

        jLabel4.setText("Cargo:");

        cbCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione cargo", "Administrador", "Vendedor" }));
        cbCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCargoActionPerformed(evt);
            }
        });
        cbCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbCargoKeyPressed(evt);
            }
        });

        cbxNombre.setText("Modificar Nombre");
        cbxNombre.setEnabled(false);
        cbxNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNombreActionPerformed(evt);
            }
        });

        cbxClave.setText("Modificar Clave");
        cbxClave.setEnabled(false);
        cbxClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClaveActionPerformed(evt);
            }
        });

        cbxCargo.setText("Modificar cargo");
        cbxCargo.setEnabled(false);
        cbxCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCargoActionPerformed(evt);
            }
        });

        btnBuscarUsuario.setText("Buscar usuario");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        txtBuscarUsuario.setToolTipText("Ingrese Nombre Del Usuario");
        txtBuscarUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarUsuarioKeyTyped(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.setToolTipText("Actualizar Usuario");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnIngresar.setText("Ingresar");
        btnIngresar.setToolTipText("Ingresar Usuario");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel5.setText("Estado:");

        btnDesactivar.setText("Desactivar");
        btnDesactivar.setToolTipText("Desactivar Usuario");
        btnDesactivar.setEnabled(false);
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });

        btnActivar.setText("Activar ");
        btnActivar.setToolTipText("Activar Usuario");
        btnActivar.setEnabled(false);
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombreUsuario)
                                .addComponent(cbCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtConfirmarClave)
                                .addComponent(txtClave))
                            .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxClave)
                            .addComponent(cbxCargo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnActivar)
                                    .addComponent(cbxNombre))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBuscarUsuario)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnDesactivar))))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNombre)
                    .addComponent(btnBuscarUsuario)
                    .addComponent(txtBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxClave))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtConfirmarClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnIngresar)
                    .addComponent(btnActivar)
                    .addComponent(btnDesactivar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(46, 46, 46))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        UsuarioDao usuarioDao = new UsuarioDaoImpl();
        if (!usuarioDao.usuarioExiste(txtNombreUsuario.getText().trim())) {
            if (txtClave.getText().trim().equals(txtConfirmarClave.getText().trim())) {
                if (txtNombreUsuario.getText().trim().equals("")) {
                    JOptionPane.showMessageDialog(null, "Escriba un nombre de usuario", "Error nombre", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (txtClave.getText().trim().equals("")) {
                    JOptionPane.showMessageDialog(null, "Escriba una clave de usuario", "Error clave", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (txtConfirmarClave.getText().trim().equals("")) {
                    JOptionPane.showMessageDialog(null, "Escriba la clave nuevamente", "Error clave", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (cbCargo.getSelectedItem().toString().equals("Seleccione cargo")) {
                    JOptionPane.showMessageDialog(null, "Seleccione el cargo del usuario", "Seleccione Cargo", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                Usuario usuario1 = new Usuario();
                usuario1.setIdUsuario(0);
                usuario1.setNombre(txtNombreUsuario.getText().trim());
                usuario1.setClave(txtConfirmarClave.getText().trim());
                usuario1.setCargo(cbCargo.getSelectedItem().toString());
                usuario1.setEstado(Byte.parseByte("1"));

                boolean resp = usuarioDao.ingresar(usuario1);
                if (!resp) {
                    JOptionPane.showMessageDialog(null, "Se ingreso el usuario correctamente");
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al ingresar el usuario", "Error de ingreso", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error, ya que las claves no son iguales", "Error en la clave", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error, ya que el nombre de usuario ya existe", "Error nombre usuario", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void cbCargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbCargoKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbCargoKeyPressed

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        // TODO add your handling code here:
        UsuarioDao usuarioDao = new UsuarioDaoImpl();
        Usuario aux = new Usuario();

        if (!txtBuscarUsuario.getText().trim().equals("")) {
            aux = usuarioDao.buscar(txtBuscarUsuario.getText().trim());

            if (aux.getNombre() == null) {
                JOptionPane.showMessageDialog(null, "Error, ya que el nombre de usuario no existe", "Error nombre usuario", JOptionPane.ERROR_MESSAGE);
            } else {
                btnIngresar.setEnabled(false);
                btnActualizar.setEnabled(true);
                txtNombreUsuario.setEnabled(false);
                txtClave.setEnabled(false);
                txtConfirmarClave.setEnabled(false);
                cbCargo.setEnabled(false);
                txtNombreUsuario.setText(aux.getNombre());
                txtClave.setText(aux.getClave());
                txtConfirmarClave.setText(aux.getClave());
                cbCargo.setSelectedItem(aux.getCargo());
                cbxNombre.setEnabled(true);
                cbxClave.setEnabled(true);
                cbxCargo.setEnabled(true);
                if (aux.getEstado() == 1) {
                    lblEstado.setText("ACTIVO");
                } else {
                    lblEstado.setText("INACTIVO");
                }
                btnActivar.setEnabled(true);
                btnDesactivar.setEnabled(true);

            }
        }else{
            JOptionPane.showMessageDialog(this, "Ingrese un nombre de usuario, por favor."
                    ,"Error",JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void cbxNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNombreActionPerformed
        // TODO add your handling code here:
        if (cbxNombre.isSelected()) {
            txtNombreUsuario.setEnabled(true);
        }
    }//GEN-LAST:event_cbxNombreActionPerformed

    private void cbxClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClaveActionPerformed
        // TODO add your handling code here:
        if (cbxClave.isSelected()) {
            txtClave.setEnabled(true);
            txtConfirmarClave.setEnabled(true);
        }
    }//GEN-LAST:event_cbxClaveActionPerformed

    private void cbxCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCargoActionPerformed
        // TODO add your handling code here:
        if (cbxCargo.isSelected()) {
            cbCargo.setEnabled(true);
        }
    }//GEN-LAST:event_cbxCargoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        UsuarioDao usuarioDao = new UsuarioDaoImpl();
        if (txtClave.getText().trim().equals(txtConfirmarClave.getText().trim())) {
            if (cbCargo.getSelectedItem().toString().equals("Seleccione cargo")) {
                JOptionPane.showMessageDialog(null, "Seleccione un cargo, intentelo nuevamente.", "Error de cargo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            usuarioDao.actualizar(txtBuscarUsuario.getText().trim(), txtNombreUsuario.getText().trim(), txtClave.getText().trim(), cbCargo.getSelectedItem().toString());
            limpiar();
            JOptionPane.showMessageDialog(null, "Se actualizo correctamente");
            btnActualizar.setEnabled(false);
            btnIngresar.setEnabled(true);
            btnActivar.setEnabled(false);
            btnDesactivar.setEnabled(false);
            cbxNombre.setEnabled(false);
            cbxClave.setEnabled(false);
            cbxCargo.setEnabled(false);
            txtNombreUsuario.setEnabled(true);
            txtClave.setEnabled(true);
            txtConfirmarClave.setEnabled(true);
            cbCargo.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Error, ya que las claves no son iguales", "Error clave", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        // TODO add your handling code here:
        UsuarioDao usuarioDao = new UsuarioDaoImpl();
        String nombre = txtNombreUsuario.getText().trim();
        boolean resp = usuarioDao.activarUsuario(nombre);
        if (!resp) {
            JOptionPane.showMessageDialog(this, "Usuario activado correctamente");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "Error al activar el usuario, intentelo mas tarde o comuniquese con el adminstrador de sistemas", "Mensaje Error", JOptionPane.ERROR_MESSAGE);
            limpiar();
        }
    }//GEN-LAST:event_btnActivarActionPerformed

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        // TODO add your handling code here:
        UsuarioDao usuarioDao = new UsuarioDaoImpl();
        String nombre = txtNombreUsuario.getText().trim();
        boolean resp = usuarioDao.desactivarUsuario(nombre);
        if (!resp) {
            JOptionPane.showMessageDialog(this, "Usuario Desactivado correctamente");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "Error al desactivar el usuario, intentelo mas tarde o comuniquese con el adminstrador de sistemas", "Mensaje Error", JOptionPane.ERROR_MESSAGE);
            limpiar();
        }
    }//GEN-LAST:event_btnDesactivarActionPerformed

    private void txtBuscarUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarUsuarioKeyTyped
        // TODO add your handling code here:
        int largo = txtBuscarUsuario.getText().trim().length();
        if(largo > 19){
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscarUsuarioKeyTyped

    private void txtNombreUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreUsuarioKeyTyped
        // TODO add your handling code here:
       int largo = txtNombreUsuario.getText().trim().length();
        if(largo > 29){
            evt.consume();
        } 
    }//GEN-LAST:event_txtNombreUsuarioKeyTyped

    private void txtClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyTyped
        // TODO add your handling code here:
        int largo = txtClave.getText().trim().length();
        if(largo > 19){
            evt.consume();
        }
    }//GEN-LAST:event_txtClaveKeyTyped

    private void txtConfirmarClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmarClaveKeyTyped
        // TODO add your handling code here:
        int largo = txtConfirmarClave.getText().trim().length();
        if(largo > 19){
            evt.consume();
        }
    }//GEN-LAST:event_txtConfirmarClaveKeyTyped

    private void cbCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCargoActionPerformed

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    public void cerrar() {
        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "Desea cerrar la ventana", "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) {
            dispose();
        } else {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorAministrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorAministrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorAministrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorAministrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenedorAministrarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox cbCargo;
    private javax.swing.JCheckBox cbxCargo;
    private javax.swing.JCheckBox cbxClave;
    private javax.swing.JCheckBox cbxNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JTextField txtBuscarUsuario;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JPasswordField txtConfirmarClave;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
