/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Controlador.ConfiguracionDao;
import Controlador.ConfiguracionDaoImpl;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author alonso
 */
public class MantenedorConfiguraciones extends javax.swing.JFrame {

    /**
     * Creates new form MantenedorConfiguraciones
     */
    public MantenedorConfiguraciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxConfiguracionProd = new javax.swing.JCheckBox();
        txtConfiguracionProd = new javax.swing.JTextField();
        cbxConfiguracionDin = new javax.swing.JCheckBox();
        txtConfiguracionDin = new javax.swing.JTextField();
        btnAplicarConf = new javax.swing.JButton();
        btnCancelarConf = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuraciones");

        jLabel1.setText("Seleccione la casilla para elegir su/sus configuración/es:");

        cbxConfiguracionProd.setText("Cantidad mínima de productos en stock para dar aviso de alerta:");
        cbxConfiguracionProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxConfiguracionProdActionPerformed(evt);
            }
        });

        txtConfiguracionProd.setEnabled(false);
        txtConfiguracionProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfiguracionProdActionPerformed(evt);
            }
        });
        txtConfiguracionProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConfiguracionProdKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfiguracionProdKeyReleased(evt);
            }
        });

        cbxConfiguracionDin.setText("Cantidad de dinero en caja para dar aviso de alerta de retiro de dinero:");
        cbxConfiguracionDin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxConfiguracionDinActionPerformed(evt);
            }
        });

        txtConfiguracionDin.setEnabled(false);
        txtConfiguracionDin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConfiguracionDinKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfiguracionDinKeyReleased(evt);
            }
        });

        btnAplicarConf.setText("Aplicar");
        btnAplicarConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarConfActionPerformed(evt);
            }
        });

        btnCancelarConf.setText("Cancelar");
        btnCancelarConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarConfActionPerformed(evt);
            }
        });

        jLabel2.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxConfiguracionProd)
                                .addGap(44, 44, 44))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxConfiguracionDin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConfiguracionDin, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConfiguracionProd, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAplicarConf, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnCancelarConf, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxConfiguracionProd)
                    .addComponent(txtConfiguracionProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxConfiguracionDin)
                    .addComponent(txtConfiguracionDin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAplicarConf)
                    .addComponent(btnCancelarConf))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarConfActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarConfActionPerformed

    private void cbxConfiguracionProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxConfiguracionProdActionPerformed
        // TODO add your handling code here:
        if(cbxConfiguracionProd.isSelected())
        {
            txtConfiguracionProd.setEnabled(true);
        }
        else txtConfiguracionProd.setEnabled(false);
    }//GEN-LAST:event_cbxConfiguracionProdActionPerformed

    private void cbxConfiguracionDinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxConfiguracionDinActionPerformed
        // TODO add your handling code here:
        if(cbxConfiguracionDin.isSelected())
        {
            txtConfiguracionDin.setEnabled(true);
        }
        else txtConfiguracionDin.setEnabled(false);
    }//GEN-LAST:event_cbxConfiguracionDinActionPerformed

    private void txtConfiguracionProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfiguracionProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfiguracionProdActionPerformed

    private void btnAplicarConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarConfActionPerformed
        // TODO add your handling code here:
        String real1, auxiliar1 = txtConfiguracionProd.getText().trim();
        real1 = auxiliar1.replace(".","");
        String real2, auxiliar2 = txtConfiguracionDin.getText().trim();
        real2 = auxiliar2.replace(".","");
        
        int cant_prod_nueva = Integer.parseInt(real1);
        int cant_din_nueva = Integer.parseInt(real2);
        
        //Verificamos que los valores nuevas de ambas variables sea mayor que cero.
        if(cant_prod_nueva >= 0 && cant_din_nueva > 0)
        {
            ConfiguracionDao config = new ConfiguracionDaoImpl();
            
            if(!cbxConfiguracionDin.isSelected() && !cbxConfiguracionProd.isSelected())
            {
                JOptionPane.showMessageDialog(null, "Seleccione alguna de las opciones porfavor.", "Boton Aplicar", JOptionPane.ERROR_MESSAGE);
            }
            
            if (cbxConfiguracionProd.isSelected()  && !cbxConfiguracionDin.isSelected())
            {
                //Actualizar la cantidad minima de productos.
                boolean resp = config.actualizarProdMin(cant_prod_nueva);
                
                if(!config.actualizarProdMin(cant_prod_nueva))
                {
                    txtConfiguracionProd.setEnabled(false);
                    cbxConfiguracionProd.setSelected(false);
                    JOptionPane.showMessageDialog(this, "Cantidad de producto actualizado correctamente.");
                }
            }
            
            if(cbxConfiguracionDin.isSelected() && !cbxConfiguracionProd.isSelected())
            {
                boolean resp2 = config.actualizarDineroMin(cant_din_nueva);
                
                if(!config.actualizarDineroMin(cant_din_nueva))
                {
                    txtConfiguracionDin.setEnabled(false);
                    cbxConfiguracionDin.setSelected(false);
                    JOptionPane.showMessageDialog(this, "Cantidad de dinero actualizado correctamente.");
                }
            }
            
            if(cbxConfiguracionDin.isSelected() && cbxConfiguracionProd.isSelected())
            {
                boolean resp = config.actualizarProdMin(cant_prod_nueva);
                boolean resp2 = config.actualizarDineroMin(cant_din_nueva);
                
                if (!config.actualizarProdMin(cant_prod_nueva) && !config.actualizarDineroMin(cant_din_nueva))
                {
                    txtConfiguracionProd.setEnabled(false);
                    cbxConfiguracionProd.setSelected(false);
                    txtConfiguracionDin.setEnabled(false);
                    cbxConfiguracionDin.setSelected(false);
                    JOptionPane.showMessageDialog(this, "Cantidades actualizadadas correctamente.");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Los valores deben ser siempre positivos, arreglelos porfavor.", "Boton Actualizar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAplicarConfActionPerformed

    private void txtConfiguracionProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfiguracionProdKeyReleased
        // TODO add your handling code here:
        DecimalFormat formateador = new DecimalFormat("###,###");
        String textoNuevo, texto = txtConfiguracionProd.getText().trim();
        textoNuevo = texto.replace(".", "");
        String ff = formateador.format(Double.parseDouble(textoNuevo));
        txtConfiguracionProd.setText(ff);
    }//GEN-LAST:event_txtConfiguracionProdKeyReleased

    private void txtConfiguracionDinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfiguracionDinKeyReleased
        // TODO add your handling code here:
        DecimalFormat formateador = new DecimalFormat("###,###");
        String textoNuevo, texto = txtConfiguracionDin.getText().trim();
        textoNuevo = texto.replace(".", "");
        String ff = formateador.format(Double.parseDouble(textoNuevo));
        txtConfiguracionDin.setText(ff);
    }//GEN-LAST:event_txtConfiguracionDinKeyReleased

    private void txtConfiguracionProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfiguracionProdKeyTyped
        // Metodo para validar que en la cantidad se ingresen solo numeros.
        int k = (int) evt.getKeyChar();
        if (k >= 97 && k <= 122 || k >= 65 && k <= 90) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo puede ingresar números!!!", "Error Datos", JOptionPane.ERROR_MESSAGE);
        }

        int largo = txtConfiguracionProd.getText().trim().length();
        if (largo > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_txtConfiguracionProdKeyTyped

    private void txtConfiguracionDinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfiguracionDinKeyTyped
       // Metodo para validar que en la cantidad se ingresen solo numeros.
        int k = (int) evt.getKeyChar();
        if (k >= 97 && k <= 122 || k >= 65 && k <= 90) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo puede ingresar números!!!", "Error Datos", JOptionPane.ERROR_MESSAGE);
        }

        int largo = txtConfiguracionDin.getText().trim().length();
        if (largo > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_txtConfiguracionDinKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorConfiguraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorConfiguraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorConfiguraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorConfiguraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenedorConfiguraciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicarConf;
    private javax.swing.JButton btnCancelarConf;
    private javax.swing.JCheckBox cbxConfiguracionDin;
    private javax.swing.JCheckBox cbxConfiguracionProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    protected javax.swing.JTextField txtConfiguracionDin;
    protected javax.swing.JTextField txtConfiguracionProd;
    // End of variables declaration//GEN-END:variables
}
