/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Modelo.Producto;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;
import static licanray.LicanRay.mantenedorMenuPrincipal;

/**
 *
 * @author alonso
 */
public class MantenedorActualizarPeso extends javax.swing.JFrame {

    /**
     * Creates new form MantenedorAgregarPeso
     */
    public MantenedorActualizarPeso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNombreProd = new javax.swing.JLabel();
        lblMarcaProd = new javax.swing.JLabel();
        lblPesoActual = new javax.swing.JLabel();
        lblPesoTotal = new javax.swing.JLabel();
        txtPesoNuevo = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPrecioKg = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar peso");

        jLabel1.setText("Nombre producto:");

        jLabel2.setText("Marca producto:");

        jLabel3.setText("Peso actual (Kg):");

        jLabel4.setText("Peso total (Kg):");

        jLabel5.setText("Peso nuevo (Kg):");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Ej: 5.6 (Kg)");

        jLabel7.setText("Precio por Kg:");

        jLabel8.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPesoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(lblPesoActual, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(lblMarcaProd, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(lblNombreProd, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(txtPesoNuevo)
                    .addComponent(lblPrecioKg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblNombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(lblMarcaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addComponent(lblPrecioKg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))
                            .addComponent(lblPesoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(lblPesoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPesoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        Double pesoIngresado = Double.parseDouble(txtPesoNuevo.getText().trim());
        Double pesoTotal = Double.parseDouble(lblPesoTotal.getText().trim());
        Double pesoActual = Double.parseDouble(lblPesoActual.getText().trim());
        String precioKg = lblPrecioKg.getText().trim();
        int precioKgReal = Integer.parseInt(precioKg.replace(".", ""));

        //Si el peso ingresdo es menor o igual que el peso actual podemos continuar.
        if (pesoIngresado <= pesoTotal) {
            Producto producto = mantenedorMenuPrincipal.productoDao.agregarProductoALaVenta(mantenedorMenuPrincipal.txtAgregarProducto.getText().trim());
            DefaultTableModel modelo = (DefaultTableModel) mantenedorMenuPrincipal.tbVenta.getModel();

            DecimalFormat formateador = new DecimalFormat("###,###");
            licanray.LicanRay.mantenedorMenuPrincipal.s = licanray.LicanRay.mantenedorMenuPrincipal.tbVenta.getSelectedRow();
            int sNew= licanray.LicanRay.mantenedorMenuPrincipal.s; //Fila seleccionada
            System.out.println("fila seleccionada: " +sNew);

            //Obtenemos el peso antiguo.
            //Ingresamos el valor de la cantidad que queremos cambiar.
            Double pesoViejo = licanray.LicanRay.mantenedorMenuPrincipal.listaPeso.get(sNew);
            int costoNew = (int) (producto.getPrecioCompra() * pesoIngresado);
            int costoViejo = (int) (producto.getPrecioCompra() * pesoActual);
            int diferencia = costoNew - costoViejo;

            // se cambia la cantidad antigua por la nueva
            licanray.LicanRay.mantenedorMenuPrincipal.listaPeso.set(sNew, pesoIngresado);
            licanray.LicanRay.mantenedorMenuPrincipal.listaCostos.set(sNew, costoNew);
            licanray.LicanRay.mantenedorMenuPrincipal.lista.set(sNew, (int)(licanray.LicanRay.mantenedorMenuPrincipal.listaPeso.get(sNew) * licanray.LicanRay.mantenedorMenuPrincipal.precio.get(sNew))); //Obtenemos el subtotal nuevo.

            int subTotalNuevo = (int) (pesoIngresado * precioKgReal);
            System.out.println("subTotalNuevo: " +subTotalNuevo);
            int subTotalViejo = (int) (pesoActual * precioKgReal);
            System.out.println("subTotalViejo: " +subTotalViejo);
            
            licanray.LicanRay.mantenedorMenuPrincipal.total = licanray.LicanRay.mantenedorMenuPrincipal.getTotal() - (subTotalViejo - subTotalNuevo);
            licanray.LicanRay.mantenedorMenuPrincipal.pesoTotalProductos = licanray.LicanRay.mantenedorMenuPrincipal.pesoTotalProductos - (pesoViejo - pesoIngresado);
            licanray.LicanRay.mantenedorMenuPrincipal.costosTotales = licanray.LicanRay.mantenedorMenuPrincipal.costosTotales - (diferencia);

            String texto01 = String.valueOf(pesoIngresado);
            String texto02 = String.valueOf(subTotalNuevo);
            String ff02 = formateador.format(Double.parseDouble(texto02));

            modelo.setValueAt(texto01, sNew, 4);
            modelo.setValueAt(ff02, sNew, 5);
            modelo.fireTableDataChanged();
            
            //licanray.LicanRay.mantenedorMenuPrincipal.total = licanray.LicanRay.mantenedorMenuPrincipal.getTotal() + subTotalNuevo;
            String texto2 = String.valueOf(licanray.LicanRay.mantenedorMenuPrincipal.total);
            String ff = formateador.format(Double.parseDouble(texto2));

            licanray.LicanRay.mantenedorMenuPrincipal.lblTotal.setText(String.valueOf("$" + ff));
            licanray.LicanRay.mantenedorMenuPrincipal.limpiar();
            dispose();
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorActualizarPeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorActualizarPeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorActualizarPeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorActualizarPeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenedorActualizarPeso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    protected javax.swing.JLabel lblMarcaProd;
    protected javax.swing.JLabel lblNombreProd;
    protected javax.swing.JLabel lblPesoActual;
    protected javax.swing.JLabel lblPesoTotal;
    protected javax.swing.JLabel lblPrecioKg;
    protected javax.swing.JTextField txtPesoNuevo;
    // End of variables declaration//GEN-END:variables
}
